[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
bitflags = "2.13.2"
bytemuck = "1.25.2"
form_urlencoded = "1.2.2"
gloo-events = "0.3.0"
gloo-render = "0.3.0"
isthmus = { path = "crates/isthmus" }
isthmus-build = { path = "crates/isthmus_build" }
isthmus_macros = { path = "crates/isthmus_macros" }
isthmus_sdf = { path = "crates/isthmus_sdf" }
pollster = "1.0.1"
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
serde = { version = "1.0.229", features = ["derive"] }
smallvec = "1.16.2"
spirv-builder = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "d83e251c46a0d8e87a8b861ba984e2775e520409" }
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "d83e251c46a0d8e87a8b861ba984e2775e520409" }
syn = { version = "3", features = ["full"] }
tokio = { version = "1.53.2", default-features = false }
toml = { version = "1.1.8", default-features = false, features = [
    "parse",
    "serde",
    "std",
] }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
tracing-subscriber = "0.3.23"
wasm-bindgen = "=0.2.127"
wasm-bindgen-futures = "=0.4.77"
wayland-backend = { version = "0.3.17", features = ["rwh_06"] }
wayland-client = { version = "0.31.15", features = ["system"] }
wayland-protocols = { version = "0.32.13", features = ["client", "staging"] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
web-sys = "=0.3.104"
web-time = "1.1.0"
wgpu = { version = "30.0.1", default-features = false }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = [
    'cfg(target_arch, values("spirv"))',
] }
unused_qualifications = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

return_self_not_must_use = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
too_many_arguments = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
cast_possible_wrap = "allow"
suboptimal_flops = "allow"

absolute_paths = "warn"
arbitrary_source_item_ordering = "warn"
allow_attributes_without_reason = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
create_dir = "warn"
dbg_macro = "warn"
empty_drop = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
error_impl_error = "warn"
exit = "warn"
filetype_is_file = "warn"
float_cmp_const = "warn"
fn_to_numeric_cast_any = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
iter_over_hash_type = "warn"
lossy_float_literal = "warn"
map_err_ignore = "warn"
mem_forget = "warn"
missing_assert_message = "warn"
mixed_read_write_in_expression = "warn"
multiple_unsafe_ops_per_block = "warn"
mutex_atomic = "warn"
mutex_integer = "warn"
needless_raw_strings = "warn"
non_zero_suggestions = "warn"
panic_in_result_fn = "warn"
pathbuf_init_then_push = "warn"
precedence_bits = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_test_prefix = "warn"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
rest_pat_in_fully_bound_structs = "warn"
semicolon_inside_block = "warn"
separated_literal_suffix = "warn"
str_to_string = "warn"
string_add = "warn"
string_lit_chars_any = "warn"
suspicious_xor_used_as_pow = "warn"
tests_outside_test_module = "warn"
todo = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"
unneeded_field_pattern = "warn"
unreachable = "warn"
unused_result_ok = "warn"
verbose_file_reads = "warn"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
strip = true

[profile.release.build-override]
opt-level = 0
codegen-units = 256

[profile.dev]
opt-level = 1
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.cantus]
codegen-units = 16
debug = 1
