max_width = 120
edition = "2024"
style_edition = "2024"
newline_style = "Unix"
use_small_heuristics = "Max"
unstable_features = true
imports_granularity = "Crate"
group_imports = "One"
reorder_impl_items = true
overflow_delimited_expr = true
condense_wildcard_suffixes = true
normalize_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
format_macro_matchers = true
hex_literal_case = "Lower"
use_field_init_shorthand = true
use_try_shorthand = true
error_on_line_overflow = true
