[package]
name = "isthmus"
version = "0.1.0"
edition.workspace = true

[dependencies]
isthmus_macros.workspace = true
spirv-std.workspace = true

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
bytemuck.workspace = true
half = "2.7.1"
slotmap = "1.1.1"
smallvec.workspace = true
thiserror = "2.0.21"
web-time.workspace = true
wgpu = { workspace = true, features = ["std", "vulkan", "webgpu", "wgsl"] }

[lints]
workspace = true
