[package]
name = "isthmus"
version = "0.1.0"
edition = "2024"

[dependencies]
isthmus_macros = { path = "../isthmus_macros" }
spirv-std.workspace = true

[target.'cfg(target_arch = "spirv")'.dependencies]
glam = { workspace = true, features = ["libm"] }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
bytemuck.workspace = true
glam = { workspace = true, features = ["std"] }
half = { version = "2.7.1", default-features = false }
raw-window-handle.workspace = true
smallvec.workspace = true
slotmap = "1.1.1"
ttf-parser.workspace = true
thiserror = "2.0.20"
web-time = "1.1.0"

[target.'cfg(target_os = "linux")'.dependencies]
pollster.workspace = true
wgpu = { workspace = true, features = ["std", "vulkan", "spirv"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { workspace = true, features = ["std", "webgpu", "wgsl"] }
web-sys = { version = "0.3.105", features = ["HtmlCanvasElement"] }

[lints]
workspace = true
