use crate::{
    Program, Rect,
    glam::{Vec2, Vec4, vec4},
};
use core::ops::Deref;

/// Immutable frame data shared by stage construction and shader invocations.
#[derive(Clone, Copy)]
pub struct ShaderFrame<P: Program> {
    /// Frame time in seconds.
    pub time: f32,
    /// Surface dimensions in logical pixels.
    pub screen_size: Vec2,
    /// Conservative logical footprint of one framebuffer pixel.
    pub pixel_size: f32,
    /// Application data shared by every draw on this surface.
    pub globals: P::Globals,
}

/// One vertex's index and shared frame data.
#[derive(Clone, Copy)]
pub struct VertexInput<P: Program> {
    /// Index within the submitted triangle strip.
    pub index: u32,
    /// Frame data supplied to the stage constructor.
    pub frame: ShaderFrame<P>,
}

impl<P: Program> VertexInput<P> {
    /// Projects a logical position and supplies its texture coordinates.
    pub fn project(self, pixel: Vec2, uv: Vec2) -> Vertex {
        let ndc = pixel / self.frame.screen_size * 2.0 - 1.0;
        Vertex { position: vec4(ndc.x, -ndc.y, 0.0, 1.0), uv, outputs: () }
    }
}

/// Value returned by a vertex stage, with statically typed inter-stage outputs.
#[derive(Clone, Copy)]
pub struct Vertex<T = ()> {
    /// Homogeneous clip-space position.
    pub position: Vec4,
    /// Texture coordinates interpolated across the primitive.
    pub uv: Vec2,
    /// Additional outputs generated by the shader declaration.
    pub outputs: T,
}

impl Vertex {
    #[doc(hidden)]
    pub const fn with<T>(self, outputs: T) -> Vertex<T> {
        Vertex { position: self.position, uv: self.uv, outputs }
    }
}

/// Raster geometry and fragment preparation for a triangle strip.
pub trait Primitive<P: Program>: Copy {
    /// Named data passed from vertices to fragments.
    type Outputs: Copy;
    /// Prepared input supplied to the fragment closure.
    type Sample;
    /// Number of vertices to submit; zero suppresses the draw.
    fn vertex_count(self) -> u32;
    /// Evaluates one vertex entirely on the GPU.
    fn vertex(self, input: VertexInput<P>) -> Vertex<Self::Outputs>;
    /// Prepares shading data and antialiased coverage before user fragment evaluation.
    fn sample(self, fragment: Fragment, outputs: Self::Outputs) -> (Self::Sample, f32);
}

/// A bounded fragment sampler rasterized with an antialiasing margin.
#[derive(Clone, Copy)]
pub struct Surface<F> {
    bounds: Rect,
    sample: F,
}

/// Pairs conservative bounds with a shader returning prepared data and coverage.
pub fn surface<F>(bounds: Rect, sample: F) -> Surface<F> {
    Surface { bounds, sample }
}

/// Rasterizes conservative bounds with automatic antialiasing padding for custom fragment sampling.
pub fn raster(bounds: Rect) -> Surface<impl Fn(Vec2) -> ((), f32) + Copy> {
    surface(bounds, |_| ((), 1.0))
}

impl<P: Program, T, F: FnOnce(Vec2) -> (T, f32) + Copy> Primitive<P> for Surface<F> {
    type Outputs = ();
    type Sample = T;

    fn vertex_count(self) -> u32 {
        Primitive::<P>::vertex_count(self.bounds)
    }

    fn vertex(self, input: VertexInput<P>) -> Vertex {
        self.bounds.expanded(input.frame.pixel_size).vertex(input)
    }

    fn sample(self, fragment: Fragment, (): ()) -> (T, f32) {
        (self.sample)(fragment.pixel)
    }
}

/// A custom GPU vertex function paired with its CPU-selected draw count.
#[derive(Clone, Copy)]
pub struct Vertices<F> {
    count: u32,
    shader: F,
}

/// Constructs a custom stage; the function is not executed on the CPU.
pub const fn vertices<F>(count: u32, shader: F) -> Vertices<F> {
    Vertices { count, shader }
}

impl<P: Program, T: Copy, F: FnOnce(VertexInput<P>) -> Vertex<T> + Copy> Primitive<P> for Vertices<F> {
    type Outputs = T;
    type Sample = T;

    fn sample(self, _: Fragment, outputs: T) -> (T, f32) {
        (outputs, 1.0)
    }

    fn vertex_count(self) -> u32 {
        self.count
    }

    fn vertex(self, input: VertexInput<P>) -> Vertex<T> {
        (self.shader)(input)
    }
}

/// Marks a named vertex output as uninterpolated.
#[derive(Clone, Copy)]
pub struct Flat<T>(pub T);

/// Marks a named vertex output for perspective-correct interpolation.
#[derive(Clone, Copy)]
pub struct Smooth<T>(pub T);

/// Rasterized fragment coordinates.
#[derive(Clone, Copy)]
pub struct Fragment<T = ()> {
    /// Actual screen position in logical pixels.
    pub pixel: Vec2,
    /// Interpolated coordinates supplied by the vertex stage.
    pub uv: Vec2,
    /// Primitive-specific data, also accessible through dereferencing this fragment.
    pub sample: T,
    /// Coverage applied by the renderer after fragment evaluation.
    pub coverage: f32,
}

impl<T: Paint + Copy> Fragment<T> {
    /// Paints the main primitive, accounting for its deferred coverage exactly once.
    pub fn paint(&self, fill: Vec4, outline: Vec4) -> Vec4 {
        let color = self.sample.paint(fill, outline);
        color.with_w(color.w / self.coverage.max(f32::MIN_POSITIVE))
    }
}

impl<T> Deref for Fragment<T> {
    type Target = T;

    fn deref(&self) -> &T {
        &self.sample
    }
}

/// Composites straight RGBA foreground over background.
pub fn source_over(foreground: Vec4, background: Vec4) -> Vec4 {
    let behind = background.w * (1.0 - foreground.w);
    let alpha = foreground.w + behind;
    ((foreground.truncate() * foreground.w + background.truncate() * behind) / alpha.max(f32::MIN_POSITIVE))
        .extend(alpha)
}

/// Composes fill and outline into a covered straight RGBA colour.
pub trait Paint {
    /// Includes antialiased fill and outer coverage in the returned colour.
    fn paint(self, fill: Vec4, outline: Vec4) -> Vec4;
}
