[package]
name = "isthmus_sdf"
version = "0.1.0"
edition = "2024"

[dependencies]
isthmus = { path = "../isthmus" }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
hashbrown = { version = "0.17.1", default-features = false, features = ["default-hasher", "inline-more"] }
kurbo = "0.13.1"
skrifa = { version = "0.46.2", default-features = false, features = ["std"] }

[lints]
workspace = true
