[package]
name = "lares"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags.workspace = true
isthmus.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { version = "0.8.9", default-features = false, features = [
    "http1",
    "json",
    "tokio",
] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.7.1", default-features = false, features = ["fs"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-events.workspace = true
gloo-render.workspace = true
tokio = { workspace = true, features = ["sync"] }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Document",
    "HtmlCanvasElement",
    "PointerEvent",
    "WheelEvent",
    "Window",
    "console",
] }

[build-dependencies]
isthmus-build.workspace = true

[dev-dependencies]
image = { version = "0.25.10", default-features = false, features = ["webp"] }

[lints]
workspace = true
