use crate::{music::MAX_PLAYLIST_TARGETS, render::tempestas};
use arrayvec::ArrayVec;
use serde::{Deserialize, Serialize};
use std::{env, fs, path::PathBuf};
use tracing::warn;

#[derive(Deserialize)]
#[cfg_attr(all(debug_assertions, feature = "generate-nix"), derive(schemars::JsonSchema))]
#[serde(default)]
#[expect(clippy::struct_excessive_bools, reason = "independent user-facing toggles")]
pub struct Config {
    /// The monitor to display on.
    pub monitor: Option<String>,
    /// The layer the app should be on.
    pub layer: Layer,
    /// The corner/edge the application should anchor to.
    pub layer_anchor: LayerAnchor,
    /// The height of the bar in logical pixels.
    pub height: f32,

    /// How many minutes in the future to display in the timeline.
    pub timeline_future_minutes: f32,
    /// How many minutes before the current time to display in the timeline.
    pub timeline_past_minutes: f32,
    /// The width in logical pixels on the left where previous tracks are displayed.
    pub history_width: f32,
    /// Favourite playlists to display as buttons.
    pub playlists: ArrayVec<String, MAX_PLAYLIST_TARGETS>,
    /// Whether star ratings should be enabled.
    pub ratings_enabled: bool,
    /// Whether to show synchronized lyrics.
    pub lyrics_enabled: bool,

    /// Whether to show the weather and calendar module.
    pub tempestas_enabled: bool,
    /// Up to three IANA timezones shown with approximate city weather.
    pub timezones: ArrayVec<String, { tempestas::MAX_WORLD_CLOCKS }>,

    /// Whether to show the system status module.
    pub status_enabled: bool,

    /// Web search providers; the first is the unprefixed fallback.
    pub search_providers: Vec<SearchProvider>,
}

#[derive(Clone, Deserialize, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "generate-nix"), derive(schemars::JsonSchema))]
pub struct SearchProvider {
    /// Display name, such as `DuckDuckGo` or `GitHub`.
    pub name: String,
    /// URL containing one `{searchTerms}` placeholder.
    pub url: String,
    /// URL of the provider icon displayed by the launcher.
    pub icon: String,
    /// Prefix which selects this provider, such as `!gh`.
    pub alias: String,
}

#[derive(Clone, Copy, Deserialize, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "generate-nix"), derive(schemars::JsonSchema))]
#[serde(rename_all = "lowercase")]
pub enum Layer {
    Background,
    Bottom,
    Top,
    Overlay,
}

#[derive(Clone, Copy, Deserialize, Serialize)]
#[cfg_attr(all(debug_assertions, feature = "generate-nix"), derive(schemars::JsonSchema))]
#[serde(rename_all = "lowercase")]
pub enum LayerAnchor {
    Top,
    Bottom,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            monitor: None,
            height: 50.0,
            timezones: ArrayVec::new(),
            tempestas_enabled: true,
            status_enabled: true,
            layer: Layer::Top,
            layer_anchor: LayerAnchor::Top,
            timeline_future_minutes: 12.0,
            timeline_past_minutes: 1.5,
            history_width: 100.0,
            playlists: ArrayVec::new(),
            ratings_enabled: false,
            lyrics_enabled: true,
            search_providers: vec![SearchProvider {
                name: "DuckDuckGo".into(),
                url: "https://duckduckgo.com/?q={searchTerms}".into(),
                icon: "https://duckduckgo.com/assets/logo_header.v109.svg".into(),
                alias: "!ddg".into(),
            }],
        }
    }
}

pub fn directory() -> PathBuf {
    env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .filter(|path| path.is_absolute())
        .or_else(|| env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))
        .unwrap_or_default()
        .join("cantus")
}

pub fn load() -> Config {
    let path = directory().join("cantus.toml");
    fs::read_to_string(&path)
        .map_err(|error| error.to_string())
        .and_then(|contents| toml::from_str(&contents).map_err(|error| error.to_string()))
        .unwrap_or_else(|error| {
            warn!("Falling back to default config for {path:?}: {error}");
            Config::default()
        })
}

#[cfg(all(debug_assertions, feature = "generate-nix"))]
pub mod nix_options {
    use super::Config;
    use schemars::generate::SchemaSettings;
    use serde_json::Value;
    use std::{fmt::Write as _, fs};

    const OUTPUT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../generated-options.nix");
    const HEADER: &str = "# Generated by config.rs.\n# Do not edit this file directly.\n\n{ lib }: {\n";

    /// Writes the Nix option declarations generated from [`Config`].
    ///
    /// # Panics
    ///
    /// Panics if the generated schema has an unexpected shape or the output file cannot be written.
    pub fn generate() {
        let schema = SchemaSettings::default()
            .with(|settings| settings.inline_subschemas = true)
            .into_generator()
            .into_root_schema_for::<Config>();
        let schema = schema.as_value();
        let mut output = HEADER.to_owned();
        for (name, property) in schema["properties"].as_object().unwrap() {
            writeln!(
                output,
                "  {name} = lib.mkOption {{\n    type = {};\n    default = builtins.fromJSON {};\n    description = {};\n  }};",
                nix_type(property),
                nix_string(&property["default"].to_string()),
                nix_string(property["description"].as_str().unwrap()),
            )
            .unwrap();
        }
        output.push_str("}\n");
        fs::write(OUTPUT, output).unwrap();
    }

    fn nix_type(schema: &Value) -> String {
        if let Some(values) = schema["enum"].as_array() {
            let values = values
                .iter()
                .map(|value| format!("      {}", nix_string(value.as_str().unwrap())))
                .collect::<Vec<_>>()
                .join("\n");
            return format!("lib.types.enum [\n{values}\n    ]");
        }
        match schema["type"].as_str() {
            None => "lib.types.nullOr (lib.types.str)".into(),
            Some("string") => "lib.types.str".into(),
            Some("number") => "lib.types.number".into(),
            Some("boolean") => "lib.types.bool".into(),
            Some("array") => {
                let list = format!("lib.types.listOf ({})", nix_type(&schema["items"]));
                if let Some(max) = schema["maxItems"].as_u64() {
                    let operator = if schema["minItems"] == schema["maxItems"] { "==" } else { "<=" };
                    format!("lib.types.addCheck ({list}) (xs: builtins.length xs {operator} {max})")
                } else {
                    list
                }
            }
            Some("object") => "lib.types.attrs".into(),
            Some(kind) => panic!("unsupported config type: {kind}"),
        }
    }

    fn nix_string(value: &str) -> String {
        serde_json::to_string(value).unwrap().replace("${", "\\${")
    }
}
